# Generated by Django 4.1.2 on 2022-10-27 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_mercado_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='mercado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='product.mercado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='peso',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='quantidae',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=4),
            preserve_default=False,
        ),
    ]
