# Generated by Django 4.1.2 on 2022-10-27 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='quantidae',
            new_name='quantidade',
        ),
        migrations.AlterField(
            model_name='product',
            name='mercado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.mercado'),
        ),
    ]
